export const ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    REGISTER: '/auth/register',
    CHANGE_PASSWORD: '/auth/change-password',
    FORGOT_PASSWORD: '/auth/forgot-password',
    VERIFY_OTP: '/auth/verify-otp',
    RESET_PASSWORD: '/auth/reset-password',
  },
  USERS: {
    BASE: '/users',
    ME: '/users/me',
    ME_PREFERENCES: '/users/me/preferences',
    BY_ID: (id) => `/users/${id}`,
    BY_ROLE: (role) => `/users/role/${role}`,
    SEARCH: '/users/search',
    SUPERVISORS_BY_DISTRICT: '/users/supervisors/by-district',
    WORKERS_BY_DISTRICT: '/users/workers/by-district',
    WORKERS_BY_SUPERVISOR: (supervisorId) => `/users/workers/by-supervisor/${supervisorId}`,
    REASSIGN: (workerId, newSupervisorId) => `/users/${workerId}/reassign/${newSupervisorId}`,
  },
  BENEFICIARIES: {
    BASE: '/beneficiaries',
    BY_ID: (id) => `/beneficiaries/${id}`,
    SEARCH: '/beneficiaries/search',
  },
  CASES: {
    BASE: '/cases',
    BY_ID: (id) => `/cases/${id}`,
    BY_STATUS: (status) => `/cases/status/${status}`,
    SEARCH: '/cases/search',
  },
  CASE_ENTRIES: {
    BASE: (caseId) => `/cases/${caseId}/entries`,
    BY_ID: (caseId, id) => `/cases/${caseId}/entries/${id}`,
    SEARCH: (caseId) => `/cases/${caseId}/entries/search`,
    OVERDUE: (caseId) => `/cases/${caseId}/entries/overdue-tasks`,
  },
  INTERVENTIONS: {
    BASE: '/interventions',
    STATS: '/interventions/stats',
    MY_SCHEDULE: '/interventions/my-schedule',
    BY_ID: (id) => `/interventions/${id}`,
    BY_STATUS: (status) => `/interventions/status/${status}`,
    BY_TYPE: (type) => `/interventions/type/${type}`,
    SEARCH: '/interventions/search',
    BY_CASE: (caseId) => `/cases/${caseId}/interventions`,
    SEARCH_BY_CASE: (caseId) => `/cases/${caseId}/interventions/search`,
    STAFF: (id) => `/interventions/${id}/staff`,
    REMOVE_STAFF: (interventionId, userId) => `/interventions/${interventionId}/staff/${userId}`,
  },
  DOCUMENTS: {
    BASE: '/documents',
    BY_ID: (id) => `/documents/${id}`,
    BY_CASE: (caseId) => `/documents/case/${caseId}`,
    BY_INTERVENTION: (id) => `/documents/intervention/${id}`,
    SEARCH: '/documents/search',
    ARCHIVE: (id) => `/documents/${id}/archive`,
    DOWNLOAD: (id) => `/documents/download/${id}`,
  },
  NOTIFICATIONS: {
    BASE: '/notifications',
    BY_ID: (id) => `/notifications/${id}`,
    UNREAD: '/notifications/unread',
    UNREAD_COUNT: '/notifications/unread/count',
    SEARCH: '/notifications/search',
    MARK_READ: (id) => `/notifications/${id}/read`,
    MARK_ALL_READ: '/notifications/read-all',
  },
  MESSAGES: {
    BASE: '/messages',
    CONVERSATIONS: '/messages/conversations',
    MESSAGEABLE_USERS: '/messages/users',
    GROUPS_ALL_STAFF: '/messages/groups/all-staff',
    GROUPS_TEAM: '/messages/groups/team',
    GROUPS_RENAME: '/messages/groups/rename',
    GROUPS_AVATAR: '/messages/groups/avatar',
    UPLOAD: '/messages/upload',
    BY_ID: (id) => `/messages/${id}`,
    BY_CONVERSATION: (id) => `/messages/conversation/${id}`,
    BY_CASE: (caseId) => `/messages/case/${caseId}`,
    SEARCH: '/messages/search',
    SEARCH_CONVERSATION: (id) => `/messages/conversation/${id}/search`,
  },
  AUDIT_LOGS: {
    BASE: '/audit-logs',
    SEARCH: '/audit-logs/search',
  },
  SETTINGS: {
    BASE: '/settings',
    BY_KEY: (key) => `/settings/key/${key}`,
    CATEGORY: (cat) => `/settings/categories/${cat}`,
    CATEGORY_SEARCH: (cat) => `/settings/categories/${cat}/search`,
    SEARCH: '/settings/search',
  },
  DASHBOARD: {
    TODAY: '/social-worker/today',
  },
  SCHEDULE: {
    ITEMS: '/social-worker/schedule',
  },
  HEALTH: '/health',
  REPORTS_V2: {
    BASE: '/reports',
    MY: '/reports/my',
    TEAM: '/reports/team',
    ALL: '/reports/all',
    BY_ID: (id) => `/reports/${id}`,
    EXPORT_PDF: (id) => `/reports/${id}/export/pdf`,
    EXPORT_EXCEL: (id) => `/reports/${id}/export/excel`,
    EXPORT_WORD: (id) => `/reports/${id}/export/word`,
    FINALIZE: (id) => `/reports/${id}/finalize`,
    SUBMIT: (id) => `/reports/${id}/submit`,
    ADMIN_SUBMISSION_STATUS: '/reports/admin/submission-status',
    ADMIN_CREATE_COMBINED: '/reports/admin/combined',
    SUPERVISOR_TEAM: '/reports/supervisor-team',
  },
  ANALYTICS: {
    MY_SUMMARY: '/analytics/my-summary',
    TEAM_SUMMARY: '/analytics/team-summary',
    TEAM_EXPORT: '/analytics/team-export',
    ORG_SUMMARY: '/analytics/org-summary',
    WORKER: (id) => `/analytics/worker/${id}`,
    BENEFICIARY: (id) => `/analytics/beneficiary/${id}`,
    UNDERPERFORMERS: '/analytics/underperformers',
    DISTRICT_PERFORMANCE: '/analytics/district-performance',
    DISTRICTS_PERFORMANCE: '/analytics/districts-performance',
    TEAM_REALTIME_STATS: '/analytics/team-realtime-stats',
    DISTRICTS: '/analytics/districts',
    ORG_RECOVERY_PROGRESS: '/analytics/org-recovery-progress',
    CASE_TRENDS: '/analytics/case-trends',
    MONTHLY_BREAKDOWN: '/analytics/monthly-breakdown',
    INTERVENTION_SUCCESS: '/analytics/intervention-success',
    CASES_BY_PRIORITY: '/analytics/cases-by-priority',
    CASES_BY_TYPE: '/analytics/cases-by-type',
    SUPERVISOR_WORKERS: (supervisorId) => `/analytics/supervisor/${supervisorId}/workers`,
    EXPORT: '/analytics/export',
  },
  PERFORMANCE: {
    METRICS: '/performance/metrics',
    SUPERVISOR_WORKLOAD: '/performance/supervisor-workload',
    DETAILS: (userId) => `/performance/details/${userId}`,
    REASSIGN: '/performance/reassign',
  },
  WARNINGS: {
    BASE: '/warnings',
    RECEIVED: '/warnings/received',
    SENT: '/warnings/sent',
    UNREAD_COUNT: '/warnings/unread-count',
    RESOLVE: (id) => `/warnings/${id}/resolve`,
    WORKER: (id) => `/warnings/worker/${id}`,
  },
};
